default_settings: null
behaviors:
  Escaping:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.1
        demo_path: demos/EscaperLv0.demo
    behavioral_cloning:
      strength: 0.1
      demo_path: demos/EscaperLv0.demo
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 20000
