default_settings: null
behaviors:
  Finding:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory: 
        memory_size: 128
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.95 # Changed from 0.99, promotes short-term rewards, -> chasing
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: demos/FinderLv0.demo
      curiosity:
        strength: 0.1
    behavioral_cloning:
      strength: 0.5
      demo_path: demos/FinderLv0.demo
    max_steps: 500000
    time_horizon: 64
    summary_freq: 20000
