default_settings: null

behaviors:
  Escaping:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory:
        memory_size: 128
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.99  # promote long-term rewards, -> escaping
        strength: 1.0
      gail:
        strength: 0.1
        demo_path: demos/EscaperLv0.demo
      curiosity:
        strength: 0.1
    behavioral_cloning:
      strength: 0.1
      demo_path: demos/EscaperLv0.demo
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 20000

    # Self-play configurations
    self_play:
      save_steps: 20000  # Save policy snapshots every 20000 steps
      team_change: 100000  # Change team after 100000 trainer steps
      swap_steps: 12500  # Swap opponents every 25000 ghost steps
      play_against_latest_model_ratio: 0.5  # 50% chance to play against the latest model
      window: 10  # Use the last 10 snapshots as opponents

  Finding:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 5120
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      memory: 
        memory_size: 128
        sequence_length: 32
    reward_signals:
      extrinsic:
        gamma: 0.95  # Changed from 0.99, promotes short-term rewards, -> chasing
        strength: 1.0
      gail:
        strength: 0.1
        demo_path: demos/FinderLv0.demo
      curiosity:
        strength: 0.1
    behavioral_cloning:
      strength: 0.1
      demo_path: demos/FinderLv0.demo
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 20000

    # Self-play configurations
    self_play:
      save_steps: 20000  # Save policy snapshots every 20000 steps
      team_change: 100000  # Change team after 100000 trainer steps
      swap_steps: 50000  # Swap opponents every 25000 ghost steps
      play_against_latest_model_ratio: 0.5  # 50% chance to play against the latest model
      window: 10  # Use the last 10 snapshots as opponents
